const BSStrings = {
  "sign_in": "Sign in",
  "sign_in_with": "Sign in with",
  "or": "Or",
  "email": "Email",
  "password": "Password",
  "need_an_account": "Need an account?",
  "sign_up": "Sign up",
  "confirm_password": "Confirm password",
  "already_remember": "Already remember",
  "invalid_email_error_text": "Please enter correct email",
  "invalid_password_error_text": "Please enter correct password",
  "empty_password_error_text": "Password is required",
  "empty_email_error_text": "Email is required",
  "password_matches_error_text": "Passwords must be same",
};
